service: doggy-connect-match

provider:
  name: aws
  runtime: python3.12
  region: us-east-1
  environment:
    SWIPES_TABLE: ${self:service}-${sls:stage}-swipes
    MATCHES_TABLE: ${self:service}-${sls:stage}-matches
    MATCH_PREFERENCES_TABLE: ${self:service}-${sls:stage}-preferences
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Scan
            - dynamodb:Query
          Resource:
            - !GetAtt SwipesTable.Arn
            - !GetAtt MatchesTable.Arn
            - !GetAtt MatchPreferencesTable.Arn

plugins:
  - serverless-offline
  - serverless-dynamodb
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    useStaticCache: false
    useDownloadCache: false
  serverless-offline:
    noPrependStageInUrl: true
  serverless-dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
      convertEmptyValues: true
      noStart: true

    seed:
      local:
        sources:
          - table: swipesTable
          - table: matchesTable
          - table: matchPreferencesTable

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

resources:
  Resources:
    SwipesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.SWIPES_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: swipe_id
            AttributeType: S
        KeySchema:
          - AttributeName: swipe_id
            KeyType: HASH

    MatchesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.MATCHES_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: match_id
            AttributeType: S
        KeySchema:
          - AttributeName: match_id
            KeyType: HASH

    MatchPreferencesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.MATCH_PREFERENCES_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: pet_id
            AttributeType: S
        KeySchema:
          - AttributeName: pet_id
            KeyType: HASH